# Generated by Django 4.2.30 on 2026-06-02 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='来源名称')),
                ('url', models.URLField(blank=True, null=True, verbose_name='来源网址')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '新闻来源',
                'verbose_name_plural': '新闻来源',
            },
        ),
        migrations.CreateModel(
            name='NewsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='新闻标题')),
                ('content', models.TextField(blank=True, null=True, verbose_name='新闻内容')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='摘要')),
                ('publish_time', models.DateTimeField(verbose_name='发布时间')),
                ('source_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='来源名称')),
                ('url', models.URLField(blank=True, null=True, verbose_name='原文链接')),
                ('sentiment_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='情感得分')),
                ('sentiment_label', models.CharField(blank=True, choices=[('positive', '正面'), ('negative', '负面'), ('neutral', '中性')], max_length=10, null=True, verbose_name='情感标签')),
                ('keywords', models.TextField(blank=True, null=True, verbose_name='关键词(JSON)')),
                ('is_processed', models.BooleanField(default=False, verbose_name='是否已分析')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.newssource', verbose_name='来源')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='stocks.stockinfo', verbose_name='关联股票')),
            ],
            options={
                'verbose_name': '舆情数据',
                'verbose_name_plural': '舆情数据',
                'ordering': ['-publish_time'],
            },
        ),
        migrations.CreateModel(
            name='HotTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=100, verbose_name='话题名称')),
                ('keywords', models.TextField(verbose_name='关键词列表')),
                ('weight', models.FloatField(default=0, verbose_name='权重')),
                ('news_count', models.IntegerField(default=0, verbose_name='相关新闻数')),
                ('date', models.DateField(verbose_name='日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='stocks.stockinfo', verbose_name='关联股票')),
            ],
            options={
                'verbose_name': '热门话题',
                'verbose_name_plural': '热门话题',
                'ordering': ['-date', '-weight'],
            },
        ),
    ]
