# Generated by Django 4.2.30 on 2026-06-02 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('correlation', '相关性分析'), ('sentiment', '情感分析'), ('topic', '主题分析'), ('prediction', '预测分析')], max_length=20, verbose_name='分析类型')),
                ('analysis_date', models.DateField(verbose_name='分析日期')),
                ('start_date', models.DateField(verbose_name='分析起始日期')),
                ('end_date', models.DateField(verbose_name='分析结束日期')),
                ('correlation', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='相关系数')),
                ('p_value', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='P值')),
                ('correlation_strength', models.CharField(blank=True, max_length=20, null=True, verbose_name='相关性强度')),
                ('is_significant', models.BooleanField(default=False, verbose_name='是否显著')),
                ('avg_sentiment_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='平均情感得分')),
                ('positive_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='正面比例')),
                ('negative_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='负面比例')),
                ('main_topics', models.TextField(blank=True, null=True, verbose_name='主要主题(JSON)')),
                ('analysis_summary', models.TextField(blank=True, null=True, verbose_name='分析摘要')),
                ('result_data', models.TextField(blank=True, null=True, verbose_name='详细结果(JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='stocks.stockinfo', verbose_name='关联股票')),
            ],
            options={
                'verbose_name': '分析结果',
                'verbose_name_plural': '分析结果',
                'ordering': ['-analysis_date'],
            },
        ),
        migrations.CreateModel(
            name='SentimentTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('sentiment_score', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='情感得分')),
                ('news_count', models.IntegerField(default=0, verbose_name='新闻数量')),
                ('positive_count', models.IntegerField(default=0, verbose_name='正面新闻数')),
                ('negative_count', models.IntegerField(default=0, verbose_name='负面新闻数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentiment_trends', to='stocks.stockinfo', verbose_name='关联股票')),
            ],
            options={
                'verbose_name': '情感趋势',
                'verbose_name_plural': '情感趋势',
                'ordering': ['-date'],
                'unique_together': {('stock', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PriceCorrelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('sentiment_score', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='情感得分')),
                ('price_change', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='股价涨跌幅(%)')),
                ('volume_change', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='成交量变化(%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correlations', to='stocks.stockinfo', verbose_name='关联股票')),
            ],
            options={
                'verbose_name': '舆情-股价相关性数据',
                'verbose_name_plural': '舆情-股价相关性数据',
                'ordering': ['-date'],
                'unique_together': {('stock', 'date')},
            },
        ),
    ]
