# Generated by Django 4.2.30 on 2026-06-02 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=10, unique=True, verbose_name='股票代码')),
                ('stock_name', models.CharField(max_length=50, verbose_name='股票名称')),
                ('industry', models.CharField(blank=True, max_length=50, null=True, verbose_name='所属行业')),
                ('list_date', models.DateField(blank=True, null=True, verbose_name='上市日期')),
                ('market', models.CharField(blank=True, max_length=10, null=True, verbose_name='市场')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '股票基本信息',
                'verbose_name_plural': '股票基本信息',
                'ordering': ['stock_code'],
            },
        ),
        migrations.CreateModel(
            name='DailyQuotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField(verbose_name='交易日期')),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='开盘价')),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='收盘价')),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='最高价')),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='最低价')),
                ('volume', models.BigIntegerField(verbose_name='成交量')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='成交额')),
                ('change_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='涨跌幅(%)')),
                ('turnover_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='换手率(%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('stock_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='stocks.stockinfo', verbose_name='股票')),
            ],
            options={
                'verbose_name': '日行情数据',
                'verbose_name_plural': '日行情数据',
                'ordering': ['-trade_date'],
                'unique_together': {('stock_code', 'trade_date')},
            },
        ),
    ]
