# Generated by Django 4.2.30 on 2026-06-02 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='报告标题')),
                ('report_type', models.CharField(choices=[('pdf', 'PDF报告'), ('excel', 'Excel报告')], max_length=10, verbose_name='报告类型')),
                ('start_date', models.DateField(verbose_name='分析起始日期')),
                ('end_date', models.DateField(verbose_name='分析结束日期')),
                ('status', models.CharField(choices=[('pending', '生成中'), ('completed', '已完成'), ('failed', '生成失败')], default='pending', max_length=10, verbose_name='状态')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='报告文件')),
                ('file_size', models.IntegerField(blank=True, null=True, verbose_name='文件大小(字节)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='报告描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
            ],
            options={
                'verbose_name': '分析报告',
                'verbose_name_plural': '分析报告',
                'ordering': ['-created_at'],
            },
        ),
    ]
